/** Интерфейс мәтіндері — қазақ тілі */
export const S = {
  appName: "FOCUS.bm",
  companyBadge: "компания платформасы",
  /** Ресми веб — focus-bm.kz (келісімдер, SMS, ЭЦП ағымдары) */
  companySiteUrl: "https://focus-bm.kz/",
  companySiteLabel: "Ресми сайт: focus-bm.kz",
  tagline: "Оқу, сөйлесу, ортақтасу — бір қосымшада",
  home: "Басты бет",
  courses: "Курстар",
  chat: "Хабарламалар",
  feed: "Лента",
  dating: "Танысу",
  admin: "Әкімші",
  login: "Кіру",
  logout: "Шығу",
  register: "Тіркелу",
  email: "Электрондық пошта",
  password: "Құпия сөз",
  displayName: "Аты-жөні",
  myCourses: "Менің курстарым",
  enroll: "Жазылу",
  progress: "Прогресс",
  postPlaceholder: "Не ойлайсың?",
  publish: "Жариялау",
  likes: "ұнатулар",
  suggestions: "Ұсыныстар",
  match: "Лайк жіберу",
  conversations: "Сөйлесулер",
  newMessage: "Хабарлама",
  send: "Жіберу",
  stats: "Статистика",
  users: "Пайдаланушылар",
  e2eNote:
    "E2EE MVP: нақты өнімде Signal-протоколы + клиенттік шифрлау. Сервер тек шифрланған пакетті сақтайды.",
} as const;
